### ISSUE TITLE
Endpoint for number of available tales

### ISSUE THREAD

**Issue by swyngaard** [whole-tale/girder_wholetale#32]
I'm in the process of optimizing the pagination of tales. Currently all available tales and their data is retrieved from girder and only a subset is parsed and displayed on the current page. When the user switches to a new page of tales, all tales are requested again but only a subset is displayed. This process does not scale very well if there are thousands of tales available to the user.

Could we get an endpoint that just returns the total number of tales available to the user? We will use this information to optimize pagination.

**Comment by Xarthisius** [comment]
That's something we occasionally reiterate. Why not use the pagination mechanism that backend provides, instead of fetching everything? cc @abrinckm @ian-taylor is that something you tested and was too slow?

@swyngaard answering your question: we can of course do that. However, while getting the total number of tales is very fast, applying ACL is slow. From backend perspective you'd be doing the same operation twice, which of course would double the time spent on listing the tales...

**Comment by swyngaard** [comment]
Taking @Xarthisius considerations into account this may not be worth pursuing for now.
