### ISSUE TITLE
Re-enable HTTPS for Tales

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/girder_wholetale#59]
Let's Encrypt now supports wildcard certificates. We should re-enable https for Tale Instances as soon as Traefik adds support for it.

Blocked by:
- [x] https://github.com/containous/traefik/issues/2674

**Comment by craig-willis** [comment]
@Xarthisius I have this working on my test instance on (Nebula).  

https://dashboard.test.wholetale.org/
https://tmp-umsfo9jk2e30.test.wholetale.org/

There are a couple of caveats:
* This is only working with wildcard (i.e., OnDemand and OnHost are disable). I still need to work through how to deal with the production configuration with dashboard.
* I ran into a strange problem that one hostname is not resolvable.  I have a second Rstudio instance running http://tmp-nw2m522yjlck.test.wholetale.org/
```
$ ping tmp-nw2m522yjlck.test.wholetale.org
ping: unknown host tmp-nw2m522yjlck.test.wholetale.org
```
I don't understand why this can't be resolved, since it is part of the *.test domain.

**Comment by craig-willis** [comment]
Deployed to dev and staging.
