### ISSUE TITLE
Add a LAUNCHING state to tale instances

### ISSUE THREAD

**Issue by swyngaard** [whole-tale/girder_wholetale#95]
Currently, a tale instance can only be in a `RUNNING` or `ERROR` state. I would like to propose a new state called `LAUNCHING` that would be reflected when a tale instance is in the process of being built but has not started running yet. This state would be displayed in the dashboard when the user launches a tale. This would be especially useful if a user chooses to launch multiple tales at once. Additionally, it would be ideal if the transition from `LAUNCHING` to `RUNNING` could be broadcast to the events stream.

I'm also not exactly sure when a tale instance would be considered `RUNNING` since the default state is `RUNNING` upon instantiation.

**Comment by Xarthisius** [comment]
This touches one issue that we discussed in the past: it would be nice to migrate to `Job` model for creating Instances. It would give you immediately everything that you just described. Trick is `POST /instance` would now return `Job` model instead of `Instance`. Is that something you could tackle during this sprint?

**Comment by amoeba** [comment]
Cool idea! For most frontends, we should be able to develop a heuristic of some sort to check that the container is `RUNNING`. Should `RUNNING` be "the user of the frontend can interact with it in a meaningful way" and not something like, "the container is spawned". For Jupyter or RStudio, a `curl` + `grep` would be enough.

**Comment by Xarthisius** [comment]
@amoeba This is what we do right now before we return 200 upon instance creation:

https://github.com/whole-tale/girder_wholetale/blob/87cc02595953f44a00e47caf6035186e25f7a592/server/models/instance.py#L23-L44

**Comment by swyngaard** [comment]
@Xarthisius I'm happy to look into migrating the `Instance` creation to the `Job` model during this sprint.

**Comment by swyngaard** [comment]
Also, should an `Instance` be considered to be `RUNNING` once `_wait_for_server(url)` returns? Could the state be considered `LAUNCHING` any time before that?

**Comment by Xarthisius** [comment]
Yeah, it would be `LAUNCHING` until `_wait_for_server` returns. We could remove that 30s timeout since it's often not enough.
Jobs have the following states:

https://github.com/girder/girder/blob/195137753b74ba8b9c35be5c47dd650c14262f0f/plugins/jobs/server/constants.py#L31-L46

but they can also have a custom description as a "sub-stage".

**Comment by Xarthisius** [comment]
Fixed and released in v0.4
